//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelegramFormTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class testler
    {
        public int sira_no { get; set; }
        public Nullable<int> test_no { get; set; }
        public Nullable<int> soru_no { get; set; }
        public Nullable<int> kullanici_id { get; set; }
        public Nullable<int> a { get; set; }
        public Nullable<int> b { get; set; }
        public Nullable<int> c { get; set; }
        public Nullable<int> d { get; set; }
        public Nullable<int> e { get; set; }
        public Nullable<bool> aktif_mi { get; set; }
    }
}
